name: dbt build (ci)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create warehouse directory
        run: mkdir -p warehouse

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-duckdb==1.10.0 duckdb==1.4.2

      - name: dbt deps
        working-directory: edtech_dbt
        run: dbt deps --profiles-dir .dbt

      - name: dbt seed (ci)
        working-directory: edtech_dbt
        run: dbt seed --profiles-dir .dbt --target ci

      - name: dbt build (ci)
        working-directory: edtech_dbt
        run: dbt build --profiles-dir .dbt --target ci
